name: Run Telegram Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Пинг каждые 5 минут

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests
          
      - name: Prepare session file
        run: |
          if [ -f "session.session" ]; then
            echo "Session file exists"
          else
            touch session.session
          fi
          
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          PING_URL: "https://api.uptimerobot.com/v2/getMonitors?api_key=${{ secrets.UPTIME_ROBOT_KEY }}"
        run: |
          # Запуск бота в фоне с пингом
          nohup python bot.py > bot.log 2>&1 &
          sleep 30
          
          # Бесконечный пинг
          while true; do
            curl -s "$PING_URL" > /dev/null
            sleep 300
          done